logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%c{1}][%M][%level][%L][%msg]%n"

server:
  port: @server.port@
  servlet:
    context-path: /api/v@project.version@

spring:
  application:
    name: serviceb
  profiles:
    active: @spring.profiles.active@
  main:
    banner-mode: off
