server:
  port: ${server.port}
  servlet:
    context-path: /api/v${project.version}

spring:
  application:
    name: movie-authors
  profiles:
    active: @spring.profiles.active@
  config:
    import: "optional:configserver:http://localhost:8888"