spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "create-drop"
  datasource:
    url: "jdbc:h2:mem:ayan;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: "org.h2.Driver"
    username: "movie_authors"
    password: "movieAuthors13711?"


logging:
  level:
    org:
      springframework:
        web: DEBUG