INSERT INTO movie (id)
VALUES (1)
    , (2)
    , (3)
    , (4)
    , (5)
    , (6)
    , (7);

INSERT INTO author (id, full_name)
VALUES (1, 'Hayden Christensen')
    , (2, 'Rachel Bilson')
    , (3, 'Jamie Bell')
    , (4, 'Samuel L. Jackson')
    , (5, 'Brianne Howey')
    , (6, 'Cassidy Gifford')
    , (7, 'Olivia Draguicevich')
    , (8, 'Ken Jeong')
    , (9, 'Zach Galifianakis')
    , (10, 'Heather Graham')
    , (11, 'Jack Black')
    , (12, 'Jessica Rothe')
    , (13, 'Ruby Wylder Rivera Mod')
    , (14, 'Carey Mulligan')
    , (15, 'Susan Sarandon')
    , (16, 'Pierce Brosnan')
    , (17, 'Sophie Tur')
    , (18, 'Jennifer Lawrence')
    , (19, 'Olivia Munn');

INSERT INTO movie_author (movie, author)
VALUES (1, 1)
    , (1, 2)
    , (1, 3)
    , (1, 4)
    , (2, 5)
    , (2, 6)
    , (2, 7)
    , (3, 8)
    , (3, 9)
    , (3, 10)
    , (4, 11)
    , (5, 12)
    , (5, 13)
    , (6, 14)
    , (7, 15)
    , (7, 16);