server:
  port: @server.port@

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/AdanUrbanReyes/ayan.git"
          searchPaths: 'java/courses/microservices/properties/{application}'
          username: username
          password: password
          skipSslValidation: true