server:
  port: @server.port@

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/AdanUrbanReyes/ayan.git"
          searchPaths: 'java/courses/microservices/properties/{application}'
          username: adanurbanreyes@gmail.com
          password: A1y3a1n7?
          skipSslValidation: true