logging:
  level:
    org:
      springframework:
        web: DEBUG

feign:
  client:
    config:
      movie-information:
        url: "/api/v1.0.0/movies"
        connectTimeout: 3000
        readTimeout: 6000
      movie-authors:
        url: "/api/v1.0.0/movies"
        connectTimeout: 3000
        readTimeout: 6000
