logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%c{1}][%M][%level][%L][%msg]%n"

server:
  port: @server.port@

spring:
  application:
    name: hello-world
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@